server:
  port: 3344
spring:
  application:
    name: springcloud-study-config
  cloud:
    config:
      server:
        git:
          # uri: git@github.com:gongxings/springcloud-study-config.git
          uri: https://github.com/an-island-whale/springcloud-study-config.git
          search-paths: config-repo
          username: 2298396257@qq.com  #账号
          password: \@xuguang97.46  #密码